### ISSUE TITLE
FR: compatible to @nuxt/content-theme-docs

### ISSUE THREAD

**Issue by willin** [nuxt-modules/google-adsense#111]
## Expect

Works on the nuxt sites using `@nuxt/content-theme-docs`

---

## Behavior now

When loading, i can see the ads (weird  style), then when page loaded completely, ads gone...

When loading:

<img width="1407" alt="QQ20210325-155215@2x" src="https://user-images.githubusercontent.com/1890238/112437696-2f137000-8d82-11eb-94f7-8befc91424c9.png">

Page loaded:

<img width="1200" alt="QQ20210325-155242@2x" src="https://user-images.githubusercontent.com/1890238/112437730-376bab00-8d82-11eb-98f8-6c0ad9b799d9.png">

Source code:  <https://github.com/willin/rx.js.cool>

Demo:  <https://rx.js.cool>

---

## Extra Infos 

Versions:

```
    "@nuxt/content-theme-docs": "0.10.1",
    "@nuxtjs/google-adsense": "^1.3.0",
    "@nuxtjs/google-analytics": "^2.4.0",
    "@nuxtjs/sitemap": "^2.4.0",
    "nuxt": "^2.15.3"
```

Nuxt Config:

```js
import theme from '@nuxt/content-theme-docs';

export default theme({
  loading: { color: '#00CD81' },
  i18n: {
    locales: () => [
      {
        code: 'zh',
        iso: 'zh-CN',
        file: 'zh-CN.js',
        name: '简体中文'
      }
    ],
    defaultLocale: 'zh'
  },
  buildModules: ['@nuxtjs/google-analytics', '@nuxtjs/google-adsense', '@nuxtjs/sitemap'],
  content: {
    liveEdit: false
  },
  components: true,
  pwa: {
    manifest: {
      name: 'RxJS教程'
    }
  },
  googleAnalytics: {
    id: 'UA-33096931-4'
  },
  'google-adsense': {
    id: 'ca-pub-5059418763237956',
    pageLevelAds: true
  },
  sitemap: {
    hostname: 'https://rx.js.cool'
  }
});
```

**Comment by manniL** [comment]
I cannot see any ads on the site anymore. If the issue still exists, please ping me.
