### ISSUE TITLE
如果需要展示固定尺寸广告该如何配置ad-style呢？

### ISSUE THREAD

**Issue by sy6841042** [nuxt-modules/google-adsense#117]
大家好,我们想展示固定尺寸广告.在我们希望放置广告的位置插入组件adsbygoogle,我们这样配置

<adsbygoogle ad-slot="***"  v-bind:style="astyleObject230" />

![1](https://user-images.githubusercontent.com/82383022/115950855-5770c480-a510-11eb-9cfd-34e2b11a26fc.jpg)

date部分：
data: {
  astyleObject230: {
      display: "inline-block",
      width: "250px",
      height: "250px",
  }
}

网页端展示不是250*250的固定尺寸广告，请问该如何办？谢谢！

**Comment by manniL** [comment]
Don't use `style` but `adStyle` instead. Also take a look at `adFormat`.
