### ISSUE TITLE
Getting 400 - "Failed to load resource", When not in test mode

### ISSUE THREAD

**Issue by drewbolton** [nuxt-modules/google-adsense#118]
Anyone know of issues when testing in localhost with real google account ID and not in test mode?

I'm getting a "Failed to load resource 400" error.  However it works fine if I remove the "ad-slot" prop. But of course, without that ad slot prop and under test mode, I'm only getting test ads with that module's test account ID.

**Comment by manniL** [comment]
Hey! Could you kindly provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction) - if the issue still exists, ping me here and I reopen? 🙏
