### ISSUE TITLE
Exclude pages

### ISSUE THREAD

**Issue by kvn29** [nuxt-modules/google-adsense#121]
Hello,

Would it be possible to be able to exclude pages for automatic ads?

For example, on a login page, there is not enough content and Google Adsense calls me to order for non-compliance with the rules, because the page does not have enough content.

Thank you

**Comment by artrayd** [comment]
You can do that on ads settings page

**Comment by manniL** [comment]
This is already possible in userland by not showing ads there, see e.g. https://github.com/albionstatus/albionstatus-website/blob/ffe8a661fba2ba4f4706d1adab0b45f599a81424/components/ad/WrapperSidebar.vue
