### ISSUE TITLE
Automatic advertisement cause page error

### ISSUE THREAD

**Issue by DaZiYuan** [nuxt-modules/google-adsense#124]
After the Adsense automatic advertisement is turned on, sometimes the page will get an error.

I found that if the ad is displayed immediately before nuxt components load, there is a high probability that an error will be reported.

![image](https://user-images.githubusercontent.com/80653/118386334-52072580-b649-11eb-9bbd-0db0177d376d.png)

---

If the ad is displayed after the nuxt component is loaded, no error will be reported.

![image](https://user-images.githubusercontent.com/80653/118386342-5e8b7e00-b649-11eb-8771-b9b2e2d406b1.png)

---
error：
```
Failed to execute 'appendChild' on 'Node': This node type does not support this method
```

**Comment by SwapnilSoni1999** [comment]
Having same issue

**Comment by manniL** [comment]
Please ping if the issue still exists.
