### ISSUE TITLE
Support the new AdSense code

### ISSUE THREAD

**Issue by awronski** [nuxt-modules/google-adsense#131]
hi!

Does this module support [new version of AdSense code](https://support.google.com/adsense/answer/10627874?hl=en)?

The new AdSense code allows AdSense to trigger optimization features earlier which can improve the performance of the ads on your site. The new ad code works for both Auto ads and ad units.

Thanks!

**Comment by farnabaz** [comment]
Yes, latest version of the module uses new AdSense code (checkout #128)

**Comment by awronski** [comment]
Thank you!

Did you notice any performance improvement?

**Comment by awronski** [comment]
One more question. If I change `onPageLoad` to true does it mean that the module will not load the adsense scipt until the whole page is ready?

So this is possible big performance gain?

**Comment by farnabaz** [comment]
>  If I change onPageLoad to true does it mean that the module will not load the adsense scipt until the whole page is ready?

Yes, and indeed it helps your site's performance

**Comment by manniL** [comment]
Resolved as the new code is used.
