### ISSUE TITLE
K {message: adsbygoogle.push() error: Only one enable_page_level_ads allowed per page

### ISSUE THREAD

**Issue by YumiSuki** [nuxt-modules/google-adsense#145]
Hello Everyone, 

Today I have tried moving Google Adsense from my `head.script` inside the `nuxt.config.js` to this module and got some error as below: 
```
K {message: "adsbygoogle.push() error: Only one 'enable_page_level_ads' allowed per page.", name: 'TagError', pbr: true...
```

I am using:
-  nuxt: ^2.15.7
-  @nuxtjs/google-adsense: ^1.4.0

My nuxt.config.js:
```
  'google-adsense': {
    onPageLoad: true,
    pageLevelAds: false,
    overlayBottom: true,
    id: process.env.ADSENSE_PUB_ID,
    test: process.env.GOOGLE_ADSENSE_TEST_MODE === 'true',
  },
```

I have it deployed at [www.eztools.io](https://www.eztools.io). 

Please kindly help.

**Comment by SwapnilSoni1999** [comment]
https://github.com/nuxt-community/google-adsense-module/issues/141#issuecomment-951144947

Check this one

**Comment by manniL** [comment]
Let's track in https://github.com/nuxt-modules/google-adsense/issues/141
