### ISSUE TITLE
"adsbygoogle.push() error: All ins elements in the DOM with class=adsbygoogle already have ads in them."

### ISSUE THREAD

**Issue by bhajan3** [nuxt-modules/google-adsense#156]
I am trying to implement the google Adsense on my app. I have followed all the steps as mentioned but i did'nt know why this error is coming please can you help me how to resolve this?

![Screenshot from 2022-01-17 12-22-25](https://user-images.githubusercontent.com/88972331/149721550-790e89d5-2e59-4b42-8c73-087cd59ee079.png)

**Comment by hareku** [comment]
I have the same issue in v2.0.0.

**Comment by fontalland** [comment]
Me too. I tried to downgrade v1.4.0 but, the error still.

**Comment by bhajan3** [comment]
@fontalland  @hareku  do you find any soultion for it?

**Comment by fontalland** [comment]
> @fontalland @hareku do you find any soultion for it?

Not yet.

**Comment by i330z** [comment]
@fontalland @hareku @bhajan3 can this error be because of nuxt-link prefetch??

**Comment by SwapnilSoni1999** [comment]
i guess module is becoming outdated

**Comment by pakornthav** [comment]
Facing the same problem, Are there any updates on this issue or any workaround?

**Comment by SwapnilSoni1999** [comment]
> Facing the same problem, Are there any updates on this issue or any workaround?

i just put ad unit directly by copying from google and placed that in <client-only> and it works though

**Comment by Luschor** [comment]
Try this custom  [solution](https://code.luasoftware.com/tutorials/nuxtjs/nuxt-load-google-adsense-auto-ads/) . Works for me.

**Comment by manniL** [comment]
While this error pops up, the ads should still be shown. This can happen when adsense is trying to load new ads though existing ads are still in place.

**Comment by manniL** [comment]
I'd accept a PR for sure.

But it also shows up when ad units are placed on the page but are populated (see e.g. https://www.albionstatus.com/ - code is open source)
