### ISSUE TITLE
useRuntimeConfig is not defined error

### ISSUE THREAD

**Issue by myagizguler** [nuxt-modules/google-adsense#164]
Hello everyone, i was faced this issue now. 

I fixed it by this way.

Add
import { useRuntimeConfig } from '#imports'

to 

node_modules/@nuxtjs/google-adsense/dist/runtime/components-v3/Adsbygoogle.vue..

It is working v3.0.0-rc.6.

Have a good day.

**Comment by jacobwise** [comment]
Nice! @myagizguler Could you open a PR for this?

**Comment by myagizguler** [comment]
Sure, I will send a PR when i go home 👋

**Comment by manniL** [comment]
Should be resolved with latest patch
